/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MultiSigAccess } from "./MultiSigAccess";
export type { PatientRecordAccess } from "./PatientRecordAccess";
