/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DiagnosticControl__factory } from "./DiagnosticControl__factory";
export { DoctorManagement__factory } from "./DoctorManagement__factory";
export { InsuranceProvider__factory } from "./InsuranceProvider__factory";
export { MedAccessControl__factory } from "./MedAccessControl__factory";
export { MultiSigAccess__factory } from "./MultiSigAccess__factory";
export { PatientManagement__factory } from "./PatientManagement__factory";
