/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as diagnosticControlSol from "./DiagnosticControl.sol";
export * as doctorManagementSol from "./DoctorManagement.sol";
export * as medAccessControlSol from "./MedAccessControl.sol";
export * as multiSigAccessSol from "./MultiSigAccess.sol";
export { PatientManagement__factory } from "./PatientManagement__factory";
