/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MedAccessControl__factory } from "./MedAccessControl__factory";
export { PatientControlledAccess__factory } from "./PatientControlledAccess__factory";
