/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DiagnosticCenterRecords } from "./DiagnosticCenterRecords";
export type { DiagnosticControl } from "./DiagnosticControl";
