/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MedAccessControl } from "./MedAccessControl";
export type { PatientControlledAccess } from "./PatientControlledAccess";
