/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MultiSigAccess__factory } from "./MultiSigAccess__factory";
export { PatientRecordAccess__factory } from "./PatientRecordAccess__factory";
