/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "DiagnosticControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DiagnosticControl__factory>;
    getContractFactory(
      name: "DoctorManagement",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DoctorManagement__factory>;
    getContractFactory(
      name: "InsuranceAgentRecordManagement",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InsuranceAgentRecordManagement__factory>;
    getContractFactory(
      name: "InsuranceProvider",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InsuranceProvider__factory>;
    getContractFactory(
      name: "MedAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MedAccessControl__factory>;
    getContractFactory(
      name: "MultiSigAccess",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MultiSigAccess__factory>;
    getContractFactory(
      name: "PatientManagement",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PatientManagement__factory>;

    getContractAt(
      name: "DiagnosticControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DiagnosticControl>;
    getContractAt(
      name: "DoctorManagement",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DoctorManagement>;
    getContractAt(
      name: "InsuranceAgentRecordManagement",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.InsuranceAgentRecordManagement>;
    getContractAt(
      name: "InsuranceProvider",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.InsuranceProvider>;
    getContractAt(
      name: "MedAccessControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MedAccessControl>;
    getContractAt(
      name: "MultiSigAccess",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MultiSigAccess>;
    getContractAt(
      name: "PatientManagement",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PatientManagement>;

    deployContract(
      name: "DiagnosticControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DiagnosticControl>;
    deployContract(
      name: "DoctorManagement",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DoctorManagement>;
    deployContract(
      name: "InsuranceAgentRecordManagement",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.InsuranceAgentRecordManagement>;
    deployContract(
      name: "InsuranceProvider",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.InsuranceProvider>;
    deployContract(
      name: "MedAccessControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MedAccessControl>;
    deployContract(
      name: "MultiSigAccess",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MultiSigAccess>;
    deployContract(
      name: "PatientManagement",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PatientManagement>;

    deployContract(
      name: "DiagnosticControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DiagnosticControl>;
    deployContract(
      name: "DoctorManagement",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DoctorManagement>;
    deployContract(
      name: "InsuranceAgentRecordManagement",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.InsuranceAgentRecordManagement>;
    deployContract(
      name: "InsuranceProvider",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.InsuranceProvider>;
    deployContract(
      name: "MedAccessControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MedAccessControl>;
    deployContract(
      name: "MultiSigAccess",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MultiSigAccess>;
    deployContract(
      name: "PatientManagement",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PatientManagement>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
