/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "DiagnosticCenterRecords",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DiagnosticCenterRecords__factory>;
    getContractFactory(
      name: "HealthcareRecords",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HealthcareRecords__factory>;
    getContractFactory(
      name: "PatientControlledAccess",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PatientControlledAccess__factory>;
    getContractFactory(
      name: "PatientRecordAccess",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PatientRecordAccess__factory>;
    getContractFactory(
      name: "PatientManagement",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PatientManagement__factory>;

    getContractAt(
      name: "DiagnosticCenterRecords",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DiagnosticCenterRecords>;
    getContractAt(
      name: "HealthcareRecords",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HealthcareRecords>;
    getContractAt(
      name: "PatientControlledAccess",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PatientControlledAccess>;
    getContractAt(
      name: "PatientRecordAccess",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PatientRecordAccess>;
    getContractAt(
      name: "PatientManagement",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PatientManagement>;

    deployContract(
      name: "DiagnosticCenterRecords",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DiagnosticCenterRecords>;
    deployContract(
      name: "HealthcareRecords",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HealthcareRecords>;
    deployContract(
      name: "PatientControlledAccess",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PatientControlledAccess>;
    deployContract(
      name: "PatientRecordAccess",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PatientRecordAccess>;
    deployContract(
      name: "PatientManagement",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PatientManagement>;

    deployContract(
      name: "DiagnosticCenterRecords",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DiagnosticCenterRecords>;
    deployContract(
      name: "HealthcareRecords",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HealthcareRecords>;
    deployContract(
      name: "PatientControlledAccess",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PatientControlledAccess>;
    deployContract(
      name: "PatientRecordAccess",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PatientRecordAccess>;
    deployContract(
      name: "PatientManagement",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PatientManagement>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
