/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as diagnosticControlSol from "./DiagnosticControl.sol";
export type { diagnosticControlSol };
import type * as doctorManagementSol from "./DoctorManagement.sol";
export type { doctorManagementSol };
import type * as medAccessControlSol from "./MedAccessControl.sol";
export type { medAccessControlSol };
import type * as multiSigAccessSol from "./MultiSigAccess.sol";
export type { multiSigAccessSol };
export type { PatientManagement } from "./PatientManagement";
export * as factories from "./factories";
export type { DiagnosticCenterRecords } from "./DiagnosticControl.sol/DiagnosticCenterRecords";
export { DiagnosticCenterRecords__factory } from "./factories/DiagnosticControl.sol/DiagnosticCenterRecords__factory";
export type { HealthcareRecords } from "./DoctorManagement.sol/HealthcareRecords";
export { HealthcareRecords__factory } from "./factories/DoctorManagement.sol/HealthcareRecords__factory";
export type { PatientControlledAccess } from "./MedAccessControl.sol/PatientControlledAccess";
export { PatientControlledAccess__factory } from "./factories/MedAccessControl.sol/PatientControlledAccess__factory";
export type { PatientRecordAccess } from "./MultiSigAccess.sol/PatientRecordAccess";
export { PatientRecordAccess__factory } from "./factories/MultiSigAccess.sol/PatientRecordAccess__factory";
export { PatientManagement__factory } from "./factories/PatientManagement__factory";
