/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as insuranceProviderSol from "./InsuranceProvider.sol";
export type { insuranceProviderSol };
export type { DiagnosticControl } from "./DiagnosticControl";
export type { DoctorManagement } from "./DoctorManagement";
export type { MedAccessControl } from "./MedAccessControl";
export type { MultiSigAccess } from "./MultiSigAccess";
export type { PatientManagement } from "./PatientManagement";
export * as factories from "./factories";
export { DiagnosticControl__factory } from "./factories/DiagnosticControl__factory";
export { DoctorManagement__factory } from "./factories/DoctorManagement__factory";
export type { InsuranceAgentRecordManagement } from "./InsuranceProvider.sol/InsuranceAgentRecordManagement";
export { InsuranceAgentRecordManagement__factory } from "./factories/InsuranceProvider.sol/InsuranceAgentRecordManagement__factory";
export type { InsuranceProvider } from "./InsuranceProvider.sol/InsuranceProvider";
export { InsuranceProvider__factory } from "./factories/InsuranceProvider.sol/InsuranceProvider__factory";
export { MedAccessControl__factory } from "./factories/MedAccessControl__factory";
export { MultiSigAccess__factory } from "./factories/MultiSigAccess__factory";
export { PatientManagement__factory } from "./factories/PatientManagement__factory";
