/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { InsuranceAgentRecordManagement__factory } from "./InsuranceAgentRecordManagement__factory";
export { InsuranceProvider__factory } from "./InsuranceProvider__factory";
