/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DoctorManagement__factory } from "./DoctorManagement__factory";
export { HealthcareRecords__factory } from "./HealthcareRecords__factory";
