/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { InsuranceAgentRecordManagement } from "./InsuranceAgentRecordManagement";
export type { InsuranceProvider } from "./InsuranceProvider";
